# fly.toml app configuration file generated for frisbii on 2023-07-31T17:59:23+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "frisbii"
primary_region = "cdg"

[http_service]
  internal_port = 3747
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
